/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WriteAction =
  | RegisterUploader
  | RequestArchiving
  | SubmitArchive
  | DeleteArchiveRequest
  | DeRegisterUploader
  | Evolve;
export type CrawlType = 'domainOnly' | 'domainWithPageLinks' | 'domainAndLinks';

export interface RegisterUploader {
  friendlyName: string;
}
export interface RequestArchiving {
  endTimestamp: number;
  frequency: string;
  options: ArchiveRequestOptions;
  startTimestamp: number;
  uploaderAddress: string;
}
export interface ArchiveRequestOptions {
  crawlType: CrawlType;
  depth: number;
  urls: string[];
}
export interface SubmitArchive {
  archiveRequestId: string;
  arweaveTx: string;
  fullUrl: string;
  options: ArchiveOptions;
  screenshotTx: string;
  size: number;
  timestamp: number;
  title: string;
}
export interface ArchiveOptions {
  crawlType: CrawlType;
  depth: number;
}
export interface DeleteArchiveRequest {
  archiveId: string;
}
export interface DeRegisterUploader {}
export interface Evolve {
  value: string;
}
