/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WriteAction =
  | RegisterUploader
  | RequestArchiving
  | SubmitArchive
  | DeleteArchiveRequest
  | DeRegisterUploader
  | Evolve;

export interface RegisterUploader {
  friendlyName: string;
}
export interface RequestArchiving {
  crawlOptions: CrawlOptions;
  endTimestamp: number;
  frequency: string;
  startTimestamp: number;
  uploaderAddress: string;
}
export interface CrawlOptions {
  depth: number;
  domainOnly: boolean;
  urls: string[];
}
export interface SubmitArchive {
  archiveRequestId: string;
  arweaveTx: string;
  fullUrl: string;
  options: ArchiveOptions;
  size: number;
  timestamp: number;
}
export interface ArchiveOptions {
  depth: number;
  domainOnly: boolean;
}
export interface DeleteArchiveRequest {
  archiveId: string;
}
export interface DeRegisterUploader {}
export interface Evolve {
  value: string;
}
